export const DEFAULT_BANNER = '// Generated by @ozaco/client codegen — do not edit.'
export const DEFAULT_EFFECT_MODULE = '@ozaco/std/effect'
export const INDENT = '  '
export const IDENTIFIER = /^[A-Za-z_$][\w$]*$/u
