/**
 * Embed the built console (`dist/index.html`) as a generated TS module the observe plugin
 * serves. Usage: `bun run scripts/embed.ts <target.ts>` after `moon run observe:build`. Every
 * `</` is written as `<\/` so the module text never contains `</script`.
 */
const distFile = `${import.meta.dir}/../dist/index.html`
const target = process.argv[2]

const dist = Bun.file(distFile)
if (!(await dist.exists())) {
  throw new Error(`missing ${distFile} — run \`moon run observe:build\` first`)
}
if (target === undefined) {
  throw new Error('usage: bun run scripts/embed.ts <target-path.ts>')
}
const html = await dist.text()
const literal = JSON.stringify(html).replaceAll('</', String.raw`<\/`)
const banner =
  '// generated by apps/observe — do not edit; regenerate with `moon run observe:embed`'
await Bun.write(target, `${banner}\nexport const CONSOLE_HTML: string = ${literal}\n`)
console.log(`wrote ${target} (html ${html.length} bytes)`)
