$schema: https://moonrepo.dev/schemas/tasks.json

implicitInputs:
  - package.json
  - tsconfig.json
  - tsconfig.base.json

fileGroups:
  configs:
    - '*.config.{js,cjs,mjs}'
    - '*.json'
  sources:
    - src/**/*
    - packages/**/*
    - plugins/**/*
    - types/**/*
  tests:
    - tests/**/*
    - '**/__tests__/**/*'
  assets:
    - assets/**/*
    - images/**/*
    - static/**/*
    - '**/*.{scss,css}'

tasks:
  clean:
    options:
      cache: false
      persistent: false
      runInCI: false
    script: rm -rf dist && rm -rf .out && rm -rf .tanstack && rm -rf coverage
    preset: server
