export enum SIGNAL_ERRORS {
  ERR_SIGNAL_CREATE = 'ERR_SIGNAL_CREATE',
  ERR_SIGNAL_SUBSCRIBE = 'ERR_SIGNAL_SUBSCRIBE',
  ERR_SIGNAL_EMIT = 'ERR_SIGNAL_EMIT',
  ERR_SIGNAL_EMIT_ASYNC = 'ERR_SIGNAL_EMIT_ASYNC',
  ERR_SIGNAL_UNSUBSCRIBE = 'ERR_SIGNAL_UNSUBSCRIBE',
  ERR_SIGNAL_CLEAR = 'ERR_SIGNAL_CLEAR',
}
