import type { Operation } from 'std:effect'
import { until } from 'std:effect'
import { fail } from 'std:result'

import { ClientErrors } from '../core/errors'
import type { ManifestDef } from '../core/types/manifest'

import { schemaToType } from './schema-to-ts'
import type { GenerateOptions } from './types'

const DEFAULT_BANNER = '// Generated by @ozaco/client codegen — do not edit.'
const DEFAULT_EFFECT_MODULE = '@ozaco/std/effect'
const INDENT = '  '
const IDENTIFIER = /^[A-Za-z_$][\w$]*$/u

const isRecord = (value: unknown): value is Record<string, unknown> =>
  typeof value === 'object' && value !== null && !Array.isArray(value)

/** A bare identifier stays bare; anything else is emitted as a quoted string literal. */
const keyText = (key: string): string =>
  IDENTIFIER.test(key)
    ? key
    : `'${key.replaceAll('\\', String.raw`\\`).replaceAll("'", String.raw`\'`)}'`

/** The TS type of one plane: values from their schema, streams by brand. */
const planeType = (plane: ManifestDef.Plane, depth: number, uses: { flow: boolean }): string => {
  if (plane.plane === 'none') {
    return 'undefined'
  }

  if (plane.plane === 'parts') {
    const streams = Object.keys(plane.streams ?? {})
      .toSorted()
      .map(name => `${keyText(name)}: Blob | Uint8Array | string`)

    return `{ fields: ${schemaToType(plane.schema, depth + 1)}; streams: { ${streams.join('; ')} } }`
  }

  if (plane.plane === 'stream') {
    if (plane.brand === 'ndjson' || plane.brand === 'sse') {
      uses.flow = true
      return `Flow<${schemaToType(plane.schema, depth + 1)}, void>`
    }

    if (plane.brand === 'text') {
      return 'string'
    }

    return 'ReadableStream<Uint8Array>'
  }

  return schemaToType(plane.schema, depth + 1)
}

const actionType = (action: ManifestDef.Action, depth: number, uses: { flow: boolean }): string => {
  const inner = INDENT.repeat(depth + 1)

  const lines = [
    `${inner}readonly kind: '${action.kind}'`,
    `${inner}readonly input: ${planeType(action.input, depth + 1, uses)}`,
    `${inner}readonly output: ${planeType(action.output, depth + 1, uses)}`,
  ]

  return `{\n${lines.join('\n')}\n${INDENT.repeat(depth)}}`
}

const serviceType = (
  service: ManifestDef.Service,
  depth: number,
  uses: { flow: boolean },
): string => {
  const inner = INDENT.repeat(depth + 1)
  const lines = [...service.actions]
    .toSorted((left, right) => left.action.localeCompare(right.action))
    .map(
      action =>
        `${inner}readonly ${keyText(action.action)}: ${actionType(action, depth + 1, uses)}`,
    )

  return `{\n${lines.join('\n')}\n${INDENT.repeat(depth)}}`
}

const routeText = (action: ManifestDef.Action): string =>
  `{ kind: '${action.kind}', method: '${action.route.method}', path: '${action.route.path}' }`

/**
 * Compile an OZACO MANIFEST v1 into a self-contained `.ts` source: an `Api` interface (one entry
 * per action with `kind`/`input`/`output` as REAL TypeScript types from the JSON Schemas — stream
 * planes become `Flow<T, void>` / `string` / `ReadableStream<Uint8Array>` by brand, `{ declared:
 * true }` degrades to `unknown`) plus an `apiRoutes` const. Use it as
 * `createClient<Api>({ url })`. A non-manifest input fails `client.decode`.
 */
export function* generate(manifest: unknown, options?: GenerateOptions): Operation<string> {
  if (
    !isRecord(manifest) ||
    manifest['manifest'] !== 'ozaco/1' ||
    !Array.isArray(manifest['services'])
  ) {
    return yield* fail(ClientErrors.Decode, 'input is not an OZACO MANIFEST v1 document')
  }
  const document = manifest as unknown as ManifestDef.Manifest
  const services = [...document.services].toSorted((left, right) =>
    left.name.localeCompare(right.name),
  )
  const uses = { flow: false }
  const apiLines: string[] = []
  const routeLines: string[] = []
  for (const service of services) {
    apiLines.push(`${INDENT}readonly ${keyText(service.name)}: ${serviceType(service, 1, uses)}`)
    const routes = [...service.actions]
      .toSorted((left, right) => left.action.localeCompare(right.action))
      .map(action => `${INDENT}${INDENT}${keyText(action.action)}: ${routeText(action)},`)
    routeLines.push(`${INDENT}${keyText(service.name)}: {`, ...routes, `${INDENT}},`)
  }
  return [
    options?.banner ?? DEFAULT_BANNER,
    ...(uses.flow
      ? ['', `import type { Flow } from '${options?.effectModule ?? DEFAULT_EFFECT_MODULE}'`]
      : []),
    '',
    'export interface Api {',
    ...apiLines,
    '}',
    '',
    'export const apiRoutes = {',
    ...routeLines,
    '} as const',
    '',
  ].join('\n')
}

/** Fetch `GET <url>/docs/manifest` and generate the client source from it. */
export function* pull(
  url: string,
  options?: GenerateOptions & { docsPath?: string },
): Operation<string> {
  const base = url.endsWith('/') ? url.slice(0, -1) : url
  const target = `${base}${options?.docsPath ?? '/docs'}/manifest`
  const response = yield* until(fetch(target))
  if (!response.ok) {
    return yield* fail(ClientErrors.Network, `manifest: ${response.status} at ${target}`)
  }
  const manifest = yield* until(response.json())
  return yield* generate(manifest, options)
}
