import { operation } from 'std:effect'
import { Fetch } from 'std:fetch'
import { fail } from 'std:result'

import { ClientErrors } from '../core/errors'
import type { ManifestDoc, ManifestFunctionDoc, ManifestServiceDoc } from '../core/types'

import { schemaToType } from './schema-to-ts'
import type { GenerateOptions } from './types'

const DEFAULT_BANNER = '// Generated by @ozaco/client codegen — do not edit.'

const INDENT = '  '

const isRecord = (value: unknown): value is Record<string, unknown> =>
  typeof value === 'object' && value !== null && !Array.isArray(value)

const IDENTIFIER = /^[A-Za-z_$][\w$]*$/u

const keyText = (key: string): string => (IDENTIFIER.test(key) ? key : JSON.stringify(key))

const indented = (schema: unknown, depth: number): string => schemaToType(schema, depth)

const functionType = (fn: ManifestFunctionDoc, depth: number): string => {
  const inner = INDENT.repeat(depth + 1)
  const lines = [
    `${inner}readonly kind: '${fn.kind}'`,
    `${inner}readonly args: ${indented(fn.args, depth + 1)}`,
    `${inner}readonly returns: ${indented(fn.returns, depth + 1)}`,
  ]

  return `{\n${lines.join('\n')}\n${INDENT.repeat(depth)}}`
}

const serviceType = (service: ManifestServiceDoc, depth: number): string => {
  const inner = INDENT.repeat(depth + 1)
  const lines = Object.keys(service.functions)
    .toSorted()
    .map(
      key =>
        `${inner}readonly ${keyText(key)}: ${functionType(
          service.functions[key] as ManifestFunctionDoc,
          depth + 1,
        )}`,
    )

  return `{\n${lines.join('\n')}\n${INDENT.repeat(depth)}}`
}

const functionMeta = (fn: ManifestFunctionDoc): string => {
  const route = fn.route ? `{ method: '${fn.route.method}', path: '${fn.route.path}' }` : 'null'

  return `{ kind: '${fn.kind}', route: ${route} }`
}

const serviceMeta = (service: ManifestServiceDoc): string => {
  const inner = INDENT.repeat(3)
  const fns = Object.keys(service.functions)
    .toSorted()
    .map(
      key =>
        `${inner}${INDENT}${keyText(key)}: ${functionMeta(
          service.functions[key] as ManifestFunctionDoc,
        )},`,
    )

  const realtime = service.realtime ? `'${service.realtime.path}'` : 'null'

  return [
    `{`,
    `${inner}prefix: '${service.prefix}',`,
    `${inner}realtime: ${realtime},`,
    `${inner}functions: {`,
    ...fns,
    `${inner}},`,
    `${INDENT.repeat(2)}}`,
  ].join('\n')
}

/**
 * Compile an OZACO MANIFEST v1 document into a self-contained `.ts` source: an `Api` interface
 * (one entry per service fn with `kind`/`args`/`returns` as REAL TypeScript types derived from
 * the JSON Schemas — `{ declared: true }` degrades to `unknown`) plus an `apiMeta` const carrying
 * the routes and realtime paths. Shape is validated loosely; a non-manifest input throws a
 * `client.manifest` Failure.
 */
export const generate = (manifest: unknown, options?: GenerateOptions): string => {
  if (!isRecord(manifest) || manifest['ozaco'] !== '1.0' || !isRecord(manifest['services'])) {
    throw fail(ClientErrors.Manifest, 'input is not an OZACO MANIFEST v1 document')
  }

  const document = manifest as unknown as ManifestDoc
  const services = Object.keys(document.services).toSorted()

  const apiLines = services.map(
    name =>
      `${INDENT}readonly ${keyText(name)}: ${serviceType(
        document.services[name] as ManifestServiceDoc,
        1,
      )}`,
  )

  const metaLines = services.map(
    name =>
      `${INDENT}${INDENT}${keyText(name)}: ${serviceMeta(
        document.services[name] as ManifestServiceDoc,
      )},`,
  )

  return [
    options?.banner ?? DEFAULT_BANNER,
    '',
    'export interface Api {',
    ...apiLines,
    '}',
    '',
    'export const apiMeta = {',
    `${INDENT}services: {`,
    ...metaLines,
    `${INDENT}},`,
    '} as const',
    '',
  ].join('\n')
}

/**
 * Fetch `GET <url>/docs/manifest` (through the installed `Fetch` plugin) and generate the client
 * source from it — the one-shot codegen entry point for build scripts.
 */
export const pull = operation(function* (url: string, options?: GenerateOptions) {
  const base = url.endsWith('/') ? url.slice(0, -1) : url
  const response = yield* Fetch.actions.get(`${base}/docs/manifest`)
  const checked = yield* response.expect()
  const manifest = yield* checked.json()

  return generate(manifest, options)
})
