import { operation } from 'std:effect'
import { Fetch } from 'std:fetch'
import { fail } from 'std:result'

import { JsonCodec } from 'std:codec/impl/json'

import { ClientErrors } from '../core/errors'
import type { ManifestDoc, ManifestFunctionDoc, ManifestServiceDoc } from '../core/types'

import { schemaToType } from './schema-to-ts'
import type { GenerateOptions } from './types'

const DEFAULT_BANNER = '// Generated by @ozaco/client codegen — do not edit.'

const INDENT = '  '

const isRecord = (value: unknown): value is Record<string, unknown> =>
  typeof value === 'object' && value !== null && !Array.isArray(value)

const IDENTIFIER = /^[A-Za-z_$][\w$]*$/u

/** A bare identifier stays bare; anything else is emitted as a quoted string literal. */
const keyText = operation(function* (key: string) {
  return IDENTIFIER.test(key) ? key : yield* JsonCodec.actions.stringify(key)
})

const indented = (schema: unknown, depth: number): string => schemaToType(schema, depth)

const functionType = (fn: ManifestFunctionDoc, depth: number): string => {
  const inner = INDENT.repeat(depth + 1)
  const lines = [
    `${inner}readonly kind: '${fn.kind}'`,
    `${inner}readonly args: ${indented(fn.args, depth + 1)}`,
    `${inner}readonly returns: ${indented(fn.returns, depth + 1)}`,
  ]

  return `{\n${lines.join('\n')}\n${INDENT.repeat(depth)}}`
}

const serviceType = operation(function* (service: ManifestServiceDoc, depth: number) {
  const inner = INDENT.repeat(depth + 1)
  const lines: string[] = []

  for (const key of Object.keys(service.functions).toSorted()) {
    const fn = service.functions[key] as ManifestFunctionDoc

    lines.push(`${inner}readonly ${yield* keyText(key)}: ${functionType(fn, depth + 1)}`)
  }

  return `{\n${lines.join('\n')}\n${INDENT.repeat(depth)}}`
})

const functionMeta = (fn: ManifestFunctionDoc): string => {
  const route = fn.route ? `{ method: '${fn.route.method}', path: '${fn.route.path}' }` : 'null'

  return `{ kind: '${fn.kind}', route: ${route} }`
}

const serviceMeta = operation(function* (service: ManifestServiceDoc) {
  const inner = INDENT.repeat(3)
  const fns: string[] = []

  for (const key of Object.keys(service.functions).toSorted()) {
    const fn = service.functions[key] as ManifestFunctionDoc

    fns.push(`${inner}${INDENT}${yield* keyText(key)}: ${functionMeta(fn)},`)
  }

  const realtime = service.realtime ? `'${service.realtime.path}'` : 'null'

  return [
    `{`,
    `${inner}prefix: '${service.prefix}',`,
    `${inner}realtime: ${realtime},`,
    `${inner}functions: {`,
    ...fns,
    `${inner}},`,
    `${INDENT.repeat(2)}}`,
  ].join('\n')
})

/**
 * Compile an OZACO MANIFEST v1 document into a self-contained `.ts` source: an `Api` interface
 * (one entry per service fn with `kind`/`args`/`returns` as REAL TypeScript types derived from
 * the JSON Schemas — `{ declared: true }` degrades to `unknown`) plus an `apiMeta` const carrying
 * the routes and realtime paths. Shape is validated loosely; a non-manifest input fails
 * `client.manifest`. REQUIRES `JsonCodec` installed (key literals are emitted through it).
 */
export const generate = operation(function* (manifest: unknown, options?: GenerateOptions) {
  if (!isRecord(manifest) || manifest['ozaco'] !== '1.0' || !isRecord(manifest['services'])) {
    return yield* fail(ClientErrors.Manifest, 'input is not an OZACO MANIFEST v1 document')
  }

  const document = manifest as unknown as ManifestDoc
  const services = Object.keys(document.services).toSorted()
  const apiLines: string[] = []
  const metaLines: string[] = []

  for (const name of services) {
    const service = document.services[name] as ManifestServiceDoc
    const key = yield* keyText(name)

    apiLines.push(`${INDENT}readonly ${key}: ${yield* serviceType(service, 1)}`)
    metaLines.push(`${INDENT}${INDENT}${key}: ${yield* serviceMeta(service)},`)
  }

  return [
    options?.banner ?? DEFAULT_BANNER,
    '',
    'export interface Api {',
    ...apiLines,
    '}',
    '',
    'export const apiMeta = {',
    `${INDENT}services: {`,
    ...metaLines,
    `${INDENT}},`,
    '} as const',
    '',
  ].join('\n')
})

/**
 * Fetch `GET <url>/docs/manifest` (through the installed `Fetch` plugin) and generate the client
 * source from it — the one-shot codegen entry point for build scripts.
 */
export const pull = operation(function* (url: string, options?: GenerateOptions) {
  const base = url.endsWith('/') ? url.slice(0, -1) : url
  const response = yield* Fetch.actions.get(`${base}/docs/manifest`)
  const checked = yield* response.expect()
  const manifest = yield* checked.json()

  return yield* generate(manifest, options)
})
