/**
 * Embed the built panel (`dist/index.html`) as a generated TS module the docs plugin serves.
 * Usage: `bun run scripts/embed.ts <target.ts>` after `moon run panel:build`. Every `</` is
 * written as `<\/` so the module text never contains `</script`.
 */
const distFile = `${import.meta.dir}/../dist/index.html`
const target = process.argv[2]

const dist = Bun.file(distFile)
if (!(await dist.exists())) {
  throw new Error(`missing ${distFile} — run \`moon run panel:build\` first`)
}
if (target === undefined) {
  throw new Error('usage: bun run scripts/embed.ts <target-path.ts>')
}
const html = await dist.text()
const literal = JSON.stringify(html).replaceAll('</', String.raw`<\/`)
const banner = '// generated by apps/panel — do not edit; regenerate with `moon run panel:embed`'
await Bun.write(target, `${banner}\nexport const PANEL_HTML: string = ${literal}\n`)
console.log(`wrote ${target} (html ${html.length} bytes)`)
