/**
 * Embed the built panel (`dist/index.html`) as a generated TS string module for the server docs
 * plugin to serve.
 *
 * Usage: `bun run scripts/embed.ts [target-path.ts]` (after `moon run panel:build`). Without a
 * target it only prints the intended future target and writes nothing — the default deliberately
 * stays OUTSIDE packages/server until the server-integration step wires it in.
 *
 * Every `</` in the JSON literal is written as `<\/` (an equivalent escape): the decoded string is
 * byte-identical, but the module text never contains `</script`, so it stays safe to inline
 * anywhere — including inside an HTML `<script>` block.
 */
const FUTURE_TARGET = 'packages/server/src/plugin/docs/internal/panel.gen.ts'

const distFile = `${import.meta.dir}/../dist/index.html`
const target = process.argv[2]

const dist = Bun.file(distFile)

if (!(await dist.exists())) {
  throw new Error(`missing ${distFile} — run \`moon run panel:build\` first`)
}

const html = await dist.text()
const literal = JSON.stringify(html).replaceAll('</', String.raw`<\/`)
const banner = '// generated by apps/panel — do not edit; regenerate with `moon run panel:embed`'
const moduleText = `${banner}\nexport const PANEL_HTML: string = ${literal}\n`

if (target === undefined) {
  console.log(`no target given — nothing written (source: ${html.length} bytes of html)`)
  console.log(`intended future target: ${FUTURE_TARGET}`)
  console.log('usage: bun run scripts/embed.ts <target-path.ts>')
} else {
  await Bun.write(target, moduleText)
  console.log(`wrote ${target} (${moduleText.length} bytes, html ${html.length} bytes)`)
}
