export interface Pipe {
  <A>(a: A): A
  <A, B = never>(a: A, ab: (a: Awaited<A>) => B): B
  <A, B = never, C = never>(a: A, ab: (a: Awaited<A>) => B, bc: (b: Awaited<B>) => C): C
  <A, B = never, C = never, D = never>(
    a: A,
    ab: (a: Awaited<A>) => B,
    bc: (b: Awaited<B>) => C,
    cd: (c: Awaited<C>) => D,
  ): D
  <A, B = never, C = never, D = never, E = never>(
    a: A,
    ab: (a: Awaited<A>) => B,
    bc: (b: Awaited<B>) => C,
    cd: (c: Awaited<C>) => D,
    de: (d: Awaited<D>) => E,
  ): E
  <A, B = never, C = never, D = never, E = never, F = never>(
    a: A,
    ab: (a: Awaited<A>) => B,
    bc: (b: Awaited<B>) => C,
    cd: (c: Awaited<C>) => D,
    de: (d: Awaited<D>) => E,
    ef: (e: Awaited<E>) => F,
  ): F
  <A, B = never, C = never, D = never, E = never, F = never, G = never>(
    a: A,
    ab: (a: Awaited<A>) => B,
    bc: (b: Awaited<B>) => C,
    cd: (c: Awaited<C>) => D,
    de: (d: Awaited<D>) => E,
    ef: (e: Awaited<E>) => F,
    fg: (f: Awaited<F>) => G,
  ): G
  <A, B = never, C = never, D = never, E = never, F = never, G = never, H = never>(
    a: A,
    ab: (a: Awaited<A>) => B,
    bc: (b: Awaited<B>) => C,
    cd: (c: Awaited<C>) => D,
    de: (d: Awaited<D>) => E,
    ef: (e: Awaited<E>) => F,
    fg: (f: Awaited<F>) => G,
    gh: (g: Awaited<G>) => H,
  ): H
  <A, B = never, C = never, D = never, E = never, F = never, G = never, H = never, I = never>(
    a: A,
    ab: (a: Awaited<A>) => B,
    bc: (b: Awaited<B>) => C,
    cd: (c: Awaited<C>) => D,
    de: (d: Awaited<D>) => E,
    ef: (e: Awaited<E>) => F,
    fg: (f: Awaited<F>) => G,
    gh: (g: Awaited<G>) => H,
    hi: (h: Awaited<H>) => I,
  ): I
  <
    A,
    B = never,
    C = never,
    D = never,
    E = never,
    F = never,
    G = never,
    H = never,
    I = never,
    J = never,
  >(
    a: A,
    ab: (a: Awaited<A>) => B,
    bc: (b: Awaited<B>) => C,
    cd: (c: Awaited<C>) => D,
    de: (d: Awaited<D>) => E,
    ef: (e: Awaited<E>) => F,
    fg: (f: Awaited<F>) => G,
    gh: (g: Awaited<G>) => H,
    hi: (h: Awaited<H>) => I,
    ij: (i: Awaited<I>) => J,
  ): J
  <
    A,
    B = never,
    C = never,
    D = never,
    E = never,
    F = never,
    G = never,
    H = never,
    I = never,
    J = never,
    K = never,
  >(
    a: A,
    ab: (a: Awaited<A>) => B,
    bc: (b: Awaited<B>) => C,
    cd: (c: Awaited<C>) => D,
    de: (d: Awaited<D>) => E,
    ef: (e: Awaited<E>) => F,
    fg: (f: Awaited<F>) => G,
    gh: (g: Awaited<G>) => H,
    hi: (h: Awaited<H>) => I,
    ij: (i: Awaited<I>) => J,
    jk: (j: Awaited<J>) => K,
  ): K
  <
    A,
    B = never,
    C = never,
    D = never,
    E = never,
    F = never,
    G = never,
    H = never,
    I = never,
    J = never,
    K = never,
    L = never,
  >(
    a: A,
    ab: (a: Awaited<A>) => B,
    bc: (b: Awaited<B>) => C,
    cd: (c: Awaited<C>) => D,
    de: (d: Awaited<D>) => E,
    ef: (e: Awaited<E>) => F,
    fg: (f: Awaited<F>) => G,
    gh: (g: Awaited<G>) => H,
    hi: (h: Awaited<H>) => I,
    ij: (i: Awaited<I>) => J,
    jk: (j: Awaited<J>) => K,
    kl: (k: Awaited<K>) => L,
  ): L
  <
    A,
    B = never,
    C = never,
    D = never,
    E = never,
    F = never,
    G = never,
    H = never,
    I = never,
    J = never,
    K = never,
    L = never,
    M = never,
  >(
    a: A,
    ab: (a: Awaited<A>) => B,
    bc: (b: Awaited<B>) => C,
    cd: (c: Awaited<C>) => D,
    de: (d: Awaited<D>) => E,
    ef: (e: Awaited<E>) => F,
    fg: (f: Awaited<F>) => G,
    gh: (g: Awaited<G>) => H,
    hi: (h: Awaited<H>) => I,
    ij: (i: Awaited<I>) => J,
    jk: (j: Awaited<J>) => K,
    kl: (k: Awaited<K>) => L,
    lm: (l: Awaited<L>) => M,
  ): M
  <
    A,
    B = never,
    C = never,
    D = never,
    E = never,
    F = never,
    G = never,
    H = never,
    I = never,
    J = never,
    K = never,
    L = never,
    M = never,
    N = never,
  >(
    a: A,
    ab: (a: Awaited<A>) => B,
    bc: (b: Awaited<B>) => C,
    cd: (c: Awaited<C>) => D,
    de: (d: Awaited<D>) => E,
    ef: (e: Awaited<E>) => F,
    fg: (f: Awaited<F>) => G,
    gh: (g: Awaited<G>) => H,
    hi: (h: Awaited<H>) => I,
    ij: (i: Awaited<I>) => J,
    jk: (j: Awaited<J>) => K,
    kl: (k: Awaited<K>) => L,
    lm: (l: Awaited<L>) => M,
    mn: (m: Awaited<M>) => N,
  ): N
  <
    A,
    B = never,
    C = never,
    D = never,
    E = never,
    F = never,
    G = never,
    H = never,
    I = never,
    J = never,
    K = never,
    L = never,
    M = never,
    N = never,
    O = never,
  >(
    a: A,
    ab: (a: Awaited<A>) => B,
    bc: (b: Awaited<B>) => C,
    cd: (c: Awaited<C>) => D,
    de: (d: Awaited<D>) => E,
    ef: (e: Awaited<E>) => F,
    fg: (f: Awaited<F>) => G,
    gh: (g: Awaited<G>) => H,
    hi: (h: Awaited<H>) => I,
    ij: (i: Awaited<I>) => J,
    jk: (j: Awaited<J>) => K,
    kl: (k: Awaited<K>) => L,
    lm: (l: Awaited<L>) => M,
    mn: (m: Awaited<M>) => N,
    no: (n: Awaited<N>) => O,
  ): O
  <
    A,
    B = never,
    C = never,
    D = never,
    E = never,
    F = never,
    G = never,
    H = never,
    I = never,
    J = never,
    K = never,
    L = never,
    M = never,
    N = never,
    O = never,
    P = never,
  >(
    a: A,
    ab: (a: Awaited<A>) => B,
    bc: (b: Awaited<B>) => C,
    cd: (c: Awaited<C>) => D,
    de: (d: Awaited<D>) => E,
    ef: (e: Awaited<E>) => F,
    fg: (f: Awaited<F>) => G,
    gh: (g: Awaited<G>) => H,
    hi: (h: Awaited<H>) => I,
    ij: (i: Awaited<I>) => J,
    jk: (j: Awaited<J>) => K,
    kl: (k: Awaited<K>) => L,
    lm: (l: Awaited<L>) => M,
    mn: (m: Awaited<M>) => N,
    no: (n: Awaited<N>) => O,
    op: (o: Awaited<O>) => P,
  ): P
  <
    A,
    B = never,
    C = never,
    D = never,
    E = never,
    F = never,
    G = never,
    H = never,
    I = never,
    J = never,
    K = never,
    L = never,
    M = never,
    N = never,
    O = never,
    P = never,
    Q = never,
  >(
    a: A,
    ab: (a: Awaited<A>) => B,
    bc: (b: Awaited<B>) => C,
    cd: (c: Awaited<C>) => D,
    de: (d: Awaited<D>) => E,
    ef: (e: Awaited<E>) => F,
    fg: (f: Awaited<F>) => G,
    gh: (g: Awaited<G>) => H,
    hi: (h: Awaited<H>) => I,
    ij: (i: Awaited<I>) => J,
    jk: (j: Awaited<J>) => K,
    kl: (k: Awaited<K>) => L,
    lm: (l: Awaited<L>) => M,
    mn: (m: Awaited<M>) => N,
    no: (n: Awaited<N>) => O,
    op: (o: Awaited<O>) => P,
    pq: (p: Awaited<P>) => Q,
  ): Q
  <
    A,
    B = never,
    C = never,
    D = never,
    E = never,
    F = never,
    G = never,
    H = never,
    I = never,
    J = never,
    K = never,
    L = never,
    M = never,
    N = never,
    O = never,
    P = never,
    Q = never,
    R = never,
  >(
    a: A,
    ab: (a: Awaited<A>) => B,
    bc: (b: Awaited<B>) => C,
    cd: (c: Awaited<C>) => D,
    de: (d: Awaited<D>) => E,
    ef: (e: Awaited<E>) => F,
    fg: (f: Awaited<F>) => G,
    gh: (g: Awaited<G>) => H,
    hi: (h: Awaited<H>) => I,
    ij: (i: Awaited<I>) => J,
    jk: (j: Awaited<J>) => K,
    kl: (k: Awaited<K>) => L,
    lm: (l: Awaited<L>) => M,
    mn: (m: Awaited<M>) => N,
    no: (n: Awaited<N>) => O,
    op: (o: Awaited<O>) => P,
    pq: (p: Awaited<P>) => Q,
    qr: (q: Awaited<Q>) => R,
  ): R
  <
    A,
    B = never,
    C = never,
    D = never,
    E = never,
    F = never,
    G = never,
    H = never,
    I = never,
    J = never,
    K = never,
    L = never,
    M = never,
    N = never,
    O = never,
    P = never,
    Q = never,
    R = never,
    S = never,
  >(
    a: A,
    ab: (a: Awaited<A>) => B,
    bc: (b: Awaited<B>) => C,
    cd: (c: Awaited<C>) => D,
    de: (d: Awaited<D>) => E,
    ef: (e: Awaited<E>) => F,
    fg: (f: Awaited<F>) => G,
    gh: (g: Awaited<G>) => H,
    hi: (h: Awaited<H>) => I,
    ij: (i: Awaited<I>) => J,
    jk: (j: Awaited<J>) => K,
    kl: (k: Awaited<K>) => L,
    lm: (l: Awaited<L>) => M,
    mn: (m: Awaited<M>) => N,
    no: (n: Awaited<N>) => O,
    op: (o: Awaited<O>) => P,
    pq: (p: Awaited<P>) => Q,
    qr: (q: Awaited<Q>) => R,
    rs: (r: Awaited<R>) => S,
  ): S
  <
    A,
    B = never,
    C = never,
    D = never,
    E = never,
    F = never,
    G = never,
    H = never,
    I = never,
    J = never,
    K = never,
    L = never,
    M = never,
    N = never,
    O = never,
    P = never,
    Q = never,
    R = never,
    S = never,
    T = never,
  >(
    a: A,
    ab: (a: Awaited<A>) => B,
    bc: (b: Awaited<B>) => C,
    cd: (c: Awaited<C>) => D,
    de: (d: Awaited<D>) => E,
    ef: (e: Awaited<E>) => F,
    fg: (f: Awaited<F>) => G,
    gh: (g: Awaited<G>) => H,
    hi: (h: Awaited<H>) => I,
    ij: (i: Awaited<I>) => J,
    jk: (j: Awaited<J>) => K,
    kl: (k: Awaited<K>) => L,
    lm: (l: Awaited<L>) => M,
    mn: (m: Awaited<M>) => N,
    no: (n: Awaited<N>) => O,
    op: (o: Awaited<O>) => P,
    pq: (p: Awaited<P>) => Q,
    qr: (q: Awaited<Q>) => R,
    rs: (r: Awaited<R>) => S,
    st: (s: Awaited<S>) => T,
  ): T
  <
    A,
    B = never,
    C = never,
    D = never,
    E = never,
    F = never,
    G = never,
    H = never,
    I = never,
    J = never,
    K = never,
    L = never,
    M = never,
    N = never,
    O = never,
    P = never,
    Q = never,
    R = never,
    S = never,
    T = never,
    U = never,
  >(
    a: A,
    ab: (a: Awaited<A>) => B,
    bc: (b: Awaited<B>) => C,
    cd: (c: Awaited<C>) => D,
    de: (d: Awaited<D>) => E,
    ef: (e: Awaited<E>) => F,
    fg: (f: Awaited<F>) => G,
    gh: (g: Awaited<G>) => H,
    hi: (h: Awaited<H>) => I,
    ij: (i: Awaited<I>) => J,
    jk: (j: Awaited<J>) => K,
    kl: (k: Awaited<K>) => L,
    lm: (l: Awaited<L>) => M,
    mn: (m: Awaited<M>) => N,
    no: (n: Awaited<N>) => O,
    op: (o: Awaited<O>) => P,
    pq: (p: Awaited<P>) => Q,
    qr: (q: Awaited<Q>) => R,
    rs: (r: Awaited<R>) => S,
    st: (s: Awaited<S>) => T,
    tu: (t: Awaited<T>) => U,
  ): U
  <
    A,
    B = never,
    C = never,
    D = never,
    E = never,
    F = never,
    G = never,
    H = never,
    I = never,
    J = never,
    K = never,
    L = never,
    M = never,
    N = never,
    O = never,
    P = never,
    Q = never,
    R = never,
    S = never,
    T = never,
    U = never,
    V = never,
  >(
    a: A,
    ab: (a: Awaited<A>) => B,
    bc: (b: Awaited<B>) => C,
    cd: (c: Awaited<C>) => D,
    de: (d: Awaited<D>) => E,
    ef: (e: Awaited<E>) => F,
    fg: (f: Awaited<F>) => G,
    gh: (g: Awaited<G>) => H,
    hi: (h: Awaited<H>) => I,
    ij: (i: Awaited<I>) => J,
    jk: (j: Awaited<J>) => K,
    kl: (k: Awaited<K>) => L,
    lm: (l: Awaited<L>) => M,
    mn: (m: Awaited<M>) => N,
    no: (n: Awaited<N>) => O,
    op: (o: Awaited<O>) => P,
    pq: (p: Awaited<P>) => Q,
    qr: (q: Awaited<Q>) => R,
    rs: (r: Awaited<R>) => S,
    st: (s: Awaited<S>) => T,
    tu: (t: Awaited<T>) => U,
    uv: (u: Awaited<U>) => V,
  ): V
  <
    A,
    B = never,
    C = never,
    D = never,
    E = never,
    F = never,
    G = never,
    H = never,
    I = never,
    J = never,
    K = never,
    L = never,
    M = never,
    N = never,
    O = never,
    P = never,
    Q = never,
    R = never,
    S = never,
    T = never,
    U = never,
    V = never,
    W = never,
  >(
    a: A,
    ab: (a: Awaited<A>) => B,
    bc: (b: Awaited<B>) => C,
    cd: (c: Awaited<C>) => D,
    de: (d: Awaited<D>) => E,
    ef: (e: Awaited<E>) => F,
    fg: (f: Awaited<F>) => G,
    gh: (g: Awaited<G>) => H,
    hi: (h: Awaited<H>) => I,
    ij: (i: Awaited<I>) => J,
    jk: (j: Awaited<J>) => K,
    kl: (k: Awaited<K>) => L,
    lm: (l: Awaited<L>) => M,
    mn: (m: Awaited<M>) => N,
    no: (n: Awaited<N>) => O,
    op: (o: Awaited<O>) => P,
    pq: (p: Awaited<P>) => Q,
    qr: (q: Awaited<Q>) => R,
    rs: (r: Awaited<R>) => S,
    st: (s: Awaited<S>) => T,
    tu: (t: Awaited<T>) => U,
    uv: (u: Awaited<U>) => V,
    vw: (v: Awaited<V>) => W,
  ): W
  <
    A,
    B = never,
    C = never,
    D = never,
    E = never,
    F = never,
    G = never,
    H = never,
    I = never,
    J = never,
    K = never,
    L = never,
    M = never,
    N = never,
    O = never,
    P = never,
    Q = never,
    R = never,
    S = never,
    T = never,
    U = never,
    V = never,
    W = never,
    X = never,
  >(
    a: A,
    ab: (a: Awaited<A>) => B,
    bc: (b: Awaited<B>) => C,
    cd: (c: Awaited<C>) => D,
    de: (d: Awaited<D>) => E,
    ef: (e: Awaited<E>) => F,
    fg: (f: Awaited<F>) => G,
    gh: (g: Awaited<G>) => H,
    hi: (h: Awaited<H>) => I,
    ij: (i: Awaited<I>) => J,
    jk: (j: Awaited<J>) => K,
    kl: (k: Awaited<K>) => L,
    lm: (l: Awaited<L>) => M,
    mn: (m: Awaited<M>) => N,
    no: (n: Awaited<N>) => O,
    op: (o: Awaited<O>) => P,
    pq: (p: Awaited<P>) => Q,
    qr: (q: Awaited<Q>) => R,
    rs: (r: Awaited<R>) => S,
    st: (s: Awaited<S>) => T,
    tu: (t: Awaited<T>) => U,
    uv: (u: Awaited<U>) => V,
    vw: (v: Awaited<V>) => W,
    wx: (w: Awaited<W>) => X,
  ): X
  <
    A,
    B = never,
    C = never,
    D = never,
    E = never,
    F = never,
    G = never,
    H = never,
    I = never,
    J = never,
    K = never,
    L = never,
    M = never,
    N = never,
    O = never,
    P = never,
    Q = never,
    R = never,
    S = never,
    T = never,
    U = never,
    V = never,
    W = never,
    X = never,
    Y = never,
  >(
    a: A,
    ab: (a: Awaited<A>) => B,
    bc: (b: Awaited<B>) => C,
    cd: (c: Awaited<C>) => D,
    de: (d: Awaited<D>) => E,
    ef: (e: Awaited<E>) => F,
    fg: (f: Awaited<F>) => G,
    gh: (g: Awaited<G>) => H,
    hi: (h: Awaited<H>) => I,
    ij: (i: Awaited<I>) => J,
    jk: (j: Awaited<J>) => K,
    kl: (k: Awaited<K>) => L,
    lm: (l: Awaited<L>) => M,
    mn: (m: Awaited<M>) => N,
    no: (n: Awaited<N>) => O,
    op: (o: Awaited<O>) => P,
    pq: (p: Awaited<P>) => Q,
    qr: (q: Awaited<Q>) => R,
    rs: (r: Awaited<R>) => S,
    st: (s: Awaited<S>) => T,
    tu: (t: Awaited<T>) => U,
    uv: (u: Awaited<U>) => V,
    vw: (v: Awaited<V>) => W,
    wx: (w: Awaited<W>) => X,
    xy: (x: Awaited<X>) => Y,
  ): Y
  <
    A,
    B = never,
    C = never,
    D = never,
    E = never,
    F = never,
    G = never,
    H = never,
    I = never,
    J = never,
    K = never,
    L = never,
    M = never,
    N = never,
    O = never,
    P = never,
    Q = never,
    R = never,
    S = never,
    T = never,
    U = never,
    V = never,
    W = never,
    X = never,
    Y = never,
    Z = never,
  >(
    a: A,
    ab: (a: Awaited<A>) => B,
    bc: (b: Awaited<B>) => C,
    cd: (c: Awaited<C>) => D,
    de: (d: Awaited<D>) => E,
    ef: (e: Awaited<E>) => F,
    fg: (f: Awaited<F>) => G,
    gh: (g: Awaited<G>) => H,
    hi: (h: Awaited<H>) => I,
    ij: (i: Awaited<I>) => J,
    jk: (j: Awaited<J>) => K,
    kl: (k: Awaited<K>) => L,
    lm: (l: Awaited<L>) => M,
    mn: (m: Awaited<M>) => N,
    no: (n: Awaited<N>) => O,
    op: (o: Awaited<O>) => P,
    pq: (p: Awaited<P>) => Q,
    qr: (q: Awaited<Q>) => R,
    rs: (r: Awaited<R>) => S,
    st: (s: Awaited<S>) => T,
    tu: (t: Awaited<T>) => U,
    uv: (u: Awaited<U>) => V,
    vw: (v: Awaited<V>) => W,
    wx: (w: Awaited<W>) => X,
    xy: (x: Awaited<X>) => Y,
    yz: (y: Awaited<Y>) => Z,
  ): Z
}
