name: 'Publish'

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    name: 'Publish to npm'
    runs-on: 'ubuntu-latest'
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: 'actions/checkout@v7'
        with:
          fetch-depth: 0

      - uses: 'moonrepo/setup-toolchain@v0'
        with:
          auto-install: true

      - uses: 'actions/setup-node@v6'
        with:
          node-version: '25'
          registry-url: 'https://registry.npmjs.org'

      - run: 'bun install --frozen-lockfile'
      - run: 'moon run std:build server:build db:build ai:build devkit:build cli:build --color'

      - run: 'npm publish --access public || true'
        working-directory: 'packages/std'

      - run: 'npm publish --access public || true'
        working-directory: 'packages/server'

      - run: 'npm publish --access public || true'
        working-directory: 'packages/db'

      - run: 'npm publish --access public || true'
        working-directory: 'packages/ai'

      - run: 'npm publish --access public || true'
        working-directory: 'packages/devkit'

      - run: 'npm publish --access public || true'
        working-directory: 'packages/cli'
