name: 'Publish'

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    environment: production
    name: 'Publish to npm'
    runs-on: 'ubuntu-latest'
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: 'actions/checkout@v6'
        with:
          fetch-depth: 0

      - uses: 'moonrepo/setup-toolchain@v0'
        with:
          auto-install: true

      - run: 'bun install --frozen-lockfile'
      - run: 'moon run std:build server:build --color'

      - run: bun install -g npm

      - run: |
          echo "registry=https://registry.npmjs.org/" >> .npmrc
          bun pm pack
          npm publish ./*.tgz --access public
        working-directory: 'packages/std'

      - run: |
          echo "registry=https://registry.npmjs.org/" >> .npmrc
          bun pm pack
          npm publish ./*.tgz --access public
        working-directory: 'packages/server'
