import { basename, dirname, join, relative, resolve } from 'node:path'

import { dbResolve, serverResolve, stdResolve } from '@ozaco/devkit/resolve'
import type { ClientDef } from '@ozaco/server/client'
import type { Service } from '@ozaco/server/core'
import type { AnyType } from '@ozaco/std/shared'
import type { UnpluginInstance } from 'unplugin'
import { createUnplugin } from 'unplugin'

const HEADER = '// AUTO-GENERATED by @ozaco/devkit — do not edit.\n'

const lit = (value: string): string => JSON.stringify(value)

const serializeManifest = (manifest: ClientDef.Manifest): string => {
  const services = Object.keys(manifest).toSorted()
  if (services.length === 0) {
    return '{}'
  }

  const body = services
    .map(service => {
      const routes = manifest[service]!
      const entries = Object.keys(routes)
        .toSorted()
        .map(action => {
          const route = routes[action]!
          return `    ${lit(action)}: { method: ${lit(route.method)}, path: ${lit(route.path)} },`
        })
        .join('\n')
      return `  ${lit(service)}: {\n${entries}\n  },`
    })
    .join('\n')

  return `{\n${body}\n}`
}

interface ClientPluginOptions {
  /** Module exporting the services record — bundled + imported at build time (NOT by the config). */
  entry: string
  /** Named export on `entry` holding the services record. Defaults to `'services'`. */
  servicesExport?: string
  /** Directory the generated source `client.ts` is written to. Defaults to `'.ozaco/gen'`. */
  outDir?: string
  /** Directory the BUILT client (`client.js` + `client.d.ts`) is written to. Defaults to `'dist'`. */
  dist?: string
  /**
   * Import specifier the BUILT `client.d.ts` uses for the `Services` type. Defaults to
   * `'./<entry basename>'` — the sibling built declaration (e.g. `entry: './src/services'` that is
   * itself a build entry emits `dist/services.d.ts`, so the client imports `./services`).
   */
  servicesModule?: string
  /** Type-only export on the `entry` module (`export type Services = typeof services`). */
  servicesType?: string
  /** Specifier for the generic client runtime. Defaults to `'server:client'`. */
  clientModule?: string
}

/** Map a `server:*` alias to its real package; pass other specifiers through (used for built output). */
const toPackageModule = (module: string): string =>
  module.startsWith('server:') ? `@ozaco/server/${module.slice('server:'.length)}` : module

/** Relative, extensionless import path from `fromDir` to a module `toFile`. */
const relModule = (fromDir: string, toFile: string): string => {
  const rel = relative(fromDir, toFile)
    .replaceAll('\\', '/')
    .replace(/\.[cm]?[jt]s$/u, '')
  return rel.startsWith('.') ? rel : `./${rel}`
}

interface Binding {
  servicesModule: string
  servicesType: string
  clientModule: string
}

/**
 * Source `client.ts` (manifest inlined + a `createClient` bound to it) — written to `outDir` for
 * inspection. `createClient` installs the broker over the manifest and returns the typed services.
 */
const renderSource = (manifest: ClientDef.Manifest, b: Binding): string =>
  `${HEADER}import { connect } from ${lit(b.clientModule)}\n` +
  `import type { ClientDef } from ${lit(b.clientModule)}\n\n` +
  `import type { ${b.servicesType} } from ${lit(b.servicesModule)}\n\n` +
  `export const manifest = ${serializeManifest(manifest)} satisfies ClientDef.Manifest\n\n` +
  `export const createClient = (options: Omit<ClientDef.Options, 'manifest'>) =>\n` +
  `  connect<${b.servicesType}>({ ...options, manifest })\n`

/** Built `client.js` (runtime only). */
const renderDistJs = (manifest: ClientDef.Manifest, clientModule: string): string =>
  `${HEADER}import { connect } from ${lit(clientModule)}\n\n` +
  `export const manifest = ${serializeManifest(manifest)}\n\n` +
  `export const createClient = options => connect({ ...options, manifest })\n`

/** Built `client.d.ts` (types only). */
const renderDistDts = (b: Binding): string =>
  `${HEADER}import type { ClientDef } from ${lit(b.clientModule)}\n` +
  `import type { Operation } from '@ozaco/std/effect'\n\n` +
  `import type { ${b.servicesType} } from ${lit(b.servicesModule)}\n\n` +
  `export declare const manifest: ClientDef.Manifest\n` +
  `export declare const createClient: (\n` +
  `  options: Omit<ClientDef.Options, 'manifest'>,\n` +
  `) => Operation<${b.servicesType}, unknown>\n`

// unique temp name per generate() so a watch rebuild never imports a stale module from cache
let tempSeq = 0

/**
 * Generate the client SDK. Built entirely on std — `std:io` for the filesystem, `std:effect`
 * (`operation`/`run`/`until`/`ensure`) for control flow, `std:result` for errors — running the
 * whole flow on the ozaco runtime. Server/std modules are imported lazily so the bundler config
 * that registers this plugin never imports any server code, just passes string options.
 *
 * Routes are only knowable after `mount` (the `rest` settings are lazy `Future`s) and the services
 * use `server:*` aliases only the bundler resolves — so we bundle `entry` through rolldown + the
 * bundled resolve plugins (aliases resolved, `@ozaco/*` external), write a runnable temp module
 * next to the entry, import it for live service objects, then mount them on a headless gateway.
 */
const generate = async (options: ClientPluginOptions): Promise<void> => {
  // the build runs under Node (tsdown/rolldown), not Bun — use the Node impls (node:fs/node:http
  // also work under Bun, so this is universal)
  const [core, gw, effect, plugin, result, io, ioNode, logger, rolldownMod] = await Promise.all([
    import('@ozaco/server/core'),
    import('@ozaco/server/gateway/node'),
    import('@ozaco/std/effect'),
    import('@ozaco/std/plugin'),
    import('@ozaco/std/result'),
    import('@ozaco/std/io'),
    import('@ozaco/std/io/impl/node'),
    import('@ozaco/std/logger'),
    import('rolldown'),
  ])

  const { Broker, DefaultBroker, Gateway, isService } = core
  const { ensure, operation, run, until, useContext } = effect
  const { install } = plugin
  const { IO } = io
  const { rolldown } = rolldownMod

  const servicesType = options.servicesType ?? 'Services'
  const sourceClientModule = options.clientModule ?? 'server:client'
  const distClientModule = toPackageModule(sourceClientModule)

  const resolveEntry = operation(function* (entry: string) {
    const base = resolve(process.cwd(), entry)
    const candidates = [base, `${base}.ts`, `${base}.js`, `${base}/index.ts`, `${base}/index.js`]

    for (const candidate of candidates) {
      if (yield* IO.actions.exists(candidate)) {
        return candidate
      }
    }

    return yield* result.fail('client/entry', `cannot resolve entry ${lit(entry)}`)
  })

  // bundle `entry` (aliases resolved, @ozaco external), import the runnable bundle for live services
  const loadServices = operation(function* (entryFile: string) {
    const bundle = yield* until(
      rolldown({
        input: entryFile,
        plugins: [stdResolve.rolldown(), serverResolve.rolldown(), dbResolve.rolldown()],
        external: [/^@ozaco\//u],
      }),
    )
    const { output } = yield* until(bundle.generate({ format: 'esm' }))
    yield* until(bundle.close())

    const chunk = output.find((item: AnyType) => item.type === 'chunk' && item.isEntry) ?? output[0]
    tempSeq += 1
    // next to the entry so the bundle's external `@ozaco/*` imports resolve via that package's
    // node_modules (works regardless of the build's cwd)
    const tmp = join(dirname(entryFile), `.ozaco-devkit-client.${process.pid}.${tempSeq}.mjs`)
    yield* IO.actions.write(tmp, (chunk as AnyType).code)
    yield* ensure(function* () {
      yield* IO.actions.rm(tmp, { force: true })
    })

    const mod = (yield* until(import(tmp))) as Record<string, unknown>
    return mod[options.servicesExport ?? 'services'] as Record<string, Service>
  })

  const collectManifest = operation(function* () {
    const ctx = yield* useContext(Gateway.context)
    const manifest: ClientDef.Manifest = {}

    for (const route of ctx.handlers.values()) {
      if (route.setting.method === 'WS') {
        continue
      }

      const action = route.action as AnyType
      const service = isService(route.target) ? route.target.name : (action.title ?? 'root')
      const key = route.key ?? action.title ?? 'handler'

      ;(manifest[service] ??= {})[key] = {
        method: route.setting.method,
        path: route.prefix + route.setting.path,
      }
    }

    return manifest
  })

  const outcome = await run(function* () {
    yield* install(ioNode.NodeIO)
    yield* install(logger.DefaultLogger, { level: logger.LogLevel.silent })
    yield* install(DefaultBroker)
    yield* install(gw.NodeGateway, { port: 0 })

    const entryFile = yield* resolveEntry(options.entry)
    const services = yield* loadServices(entryFile)

    for (const service of Object.values(services)) {
      yield* install(service)
      yield* Broker.actions.register(service)
      yield* Gateway.actions.mount(`/${service.name}`, service)
    }

    const manifest = yield* collectManifest()

    // source `client.ts` (for inspection / typecheck) in outDir
    const outDir = resolve(process.cwd(), options.outDir ?? '.ozaco/gen')
    yield* IO.actions.ensureDir(outDir)
    yield* IO.actions.write(
      join(outDir, 'client.ts'),
      renderSource(manifest, {
        servicesModule: relModule(outDir, entryFile),
        servicesType,
        clientModule: sourceClientModule,
      }),
    )

    // BUILT client straight into dist — first-run-safe (no tsdown entry: tsdown resolves entries
    // before any plugin hook runs, so a generated-during-build file can never be an entry)
    const distDir = resolve(process.cwd(), options.dist ?? 'dist')
    yield* IO.actions.ensureDir(distDir)
    yield* IO.actions.write(join(distDir, 'client.js'), renderDistJs(manifest, distClientModule))
    yield* IO.actions.write(
      join(distDir, 'client.d.ts'),
      renderDistDts({
        // the built services declaration is a sibling in dist (when `entry` is also a build entry)
        servicesModule:
          options.servicesModule ?? `./${basename(entryFile).replace(/\.[cm]?[jt]s$/u, '')}`,
        servicesType,
        clientModule: distClientModule,
      }),
    )
  })

  if (!result.isSuccess(outcome)) {
    const failure = outcome as AnyType
    throw new Error(`@ozaco/devkit: ${String(failure.error ?? failure.message)}`)
  }
}

/**
 * Build-time client SDK generator. Add to any unplugin-compatible bundler (rolldown/tsdown, vite,
 * webpack, esbuild). On `buildStart` it bundles + imports the `entry` services module, mounts each
 * service on a headless gateway, collects the route manifest, and writes a source `client.ts`
 * (in `outDir`, default `.ozaco/gen`) plus a built `client.js` + `client.d.ts` (in `dist`). The
 * bundler config only passes strings — no server imports.
 *
 *   // tsdown.config.ts
 *   import { clientPlugin } from '@ozaco/devkit/client'
 *   export default defineConfig({
 *     plugins: [clientPlugin.rolldown({ entry: './src/services' })],
 *   })
 */
const clientPlugin: UnpluginInstance<ClientPluginOptions, false> = createUnplugin(
  (options: ClientPluginOptions) => ({
    name: '@ozaco/devkit:client',
    async buildStart() {
      await generate(options)
    },
  }),
)

export { clientPlugin, generate }
export type { ClientPluginOptions }
